ALTER TABLE Users ADD birth timestamp NOT NULL;

CREATE TABLE UsersKeywords (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    keyword varchar NOT NULL
);

ALTER TABLE UsersKeywords ADD FOREIGN KEY (user_id) REFERENCES Users (id);