ALTER TABLE Summarize ADD news_ids VARCHAR NOT NULL;
ALTER TABLE Summarize ADD created_time TIMESTAMP NOT NULL;
ALTER TABLE Summarize RENAME TO BatchResult;

CREATE TABLE SummarizeLog (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    summarize varchar NOT NULL,
    categories varchar,
    keywords varchar,
    news_ids varchar NOT NULL,
    created_time TIMESTAMP NOT NULL,
    batchnews_id int
);

ALTER TABLE SummarizeLog ADD FOREIGN KEY (user_id) REFERENCES Users (id);