task: ext
mode: test
test_from: C:\Users\son\Documents\GitHub\2023-02-CECD2-6\MultiSummary/model/model_step_20500.pt
bert_data_path: C:\Users\son\Documents\GitHub\2023-02-CECD2-6\MultiSummary/datasets/bert
result_path: C:\Users\son\Documents\GitHub\2023-02-CECD2-6\MultiSummary/results/result
log_file: C:\Users\son\Documents\GitHub\2023-02-CECD2-6\MultiSummary/results/logs/step_20500.log
test_batch_size: 1
batch_size: 3000
sep_optim: true
use_interval: true
visible_gpus: "-1"
max_pos: 512
max_length: 200
alpha: 0.95
min_length: 50
report_rouge: false
max_tgt_len: 100
make_gold: false
use_model: skt/kobert-base-v1
