spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:postgresql://10.0.139.211:5432/gds_database
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC