name: Build and Deploy to EC2

on:
  push:
    branches:
      [ main, development, feat/31 ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # env:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build --platform linux/amd64 -t $username/gds_backend:latest .
          docker push $username/gds_backend:latest

      - name: SSH into EC2 and pull the Docker image
        run: |
          ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} -i ~/.ssh/id_rsa" -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PRIVATE_IP }} "docker pull $username/gds_backend:latest"
          docker run -it --name gds_backend -p 8080:8080 $username/gds_backend:latest
